#-------------------------------
# General Site Settings

title: alu - Blogs 
description: notes, translations and thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonepture.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name: alu 
author-avatar: profile.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: alu-blog # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
